no-context/moo

moo.js, test/test.js
Property names are token names, and property values are regular expressions, e.g.:
```js
{ word: /[a-z]+/, space: / +/ } <==> [ ['word', /[a-z]+/], ['space', / +/] ]
```
Closes tjvr/moo#7.
=> Accept non-Array objects as compile() ruleset

moo.js
I'm not very good at this "JavaScript" thing.
=> Use Object.getOwnPropertyNames instead of Object.keys

README.md, moo.js, test/benchmark.js, test/python.js, test/test.js, test/tosh.js
* Return a Lexer instead of a factory -- fixes #8.
* Rename moo() -> moo.compile()
* Add Lexer::reset()
=> Rework API

moo.js, test/test.js
For #26.
This refactors compilation so that regexps with capturing groups get treated as separate rules, whereas  other regexps and literals can be combined as before.
It also makes compilation significantly slower (5,338 ops/sec vs. 8,400, on a slow machine), but since compilation is already pretty fast, that's probably okay.
=> Split out capturing RegExps from array

moo.js, test/python.js, test/test.js, test/tosh.js
A proposed scheme for #18.
By default, if no token matches, moo will throw a syntax error.
Unless you define one of your tokens to match the special pattern `moo.error`, in one of the following ways:
```js
myError: moo.error
myError: { match: moo.error }
myError: { match: [/[`$\t]/, moo.error] }
```
...in which case, moo will instead return a token object with `type: myError`, with the value being the remainder of the input buffer.
=> Add error tokens

.eslintrc.js, README.md, moo.js, test/test.js
Another go at #5.
Internally add `keywords` dict to rule options. We check this exists before using it, to avoid the dict lookup cost.
New PR since the internals have changed significantly since... 3 days ago :-)
=> Special-case keywords, take two

moo.js
As mentioned in #36
This has minimal effect on performance.
=> Don't re-compile RegExp in clone()

moo.js, test/python.js, test/test.js, test/tosh.js
=> Remove feed() and add remaining()

README.md, moo.js, test/test.js
Some thoughts on #53.
See the [updated readme](https://github.com/tjvr/moo/blob/less-magic/README.md#keywords).
=> Explicit keywords

moo.js, test/test.js
This allows writing rules in the object style, where the rules have the same `tokenType` but different properties (e.g. `lineBreaks`, or state manipulation).
e.g.
```js
STRING: [
{match: /"""[^]*?"""/, lineBreaks: true},
{match: /"(?:\\["\\]|[^"\\\n])*?"/},
{match: /'(?:\\['\\]|[^'\\\n])*?'/},
],
```
=> Accept a list of match objects

moo.js, test/test.js
Return `(?!)`, which never matches anything (as mentioned in #91).
=> Fix reUnion() for empty regex lists

moo.js, test/test.js
Upon further consideration, #88 seems like a good idea. Markdown(ish) syntaxes are the obvious motivating example: arbitrary text with certain embedded sequences have special meanings, and incomplete special sequences should be passed through verbatim.
```js
const lexer = moo.compile({
para: {lineBreaks: true, match: /(?:\r?\n|\r){2,}/},
issu: {match: /#\d+/, value: s => s.slice(1)},
lstr: /\*\*(?=\S)|__(?=\S)/,
rstr: /\*\*(?=\s|$)|__(?=\s|$)/,
escp: {match: /\\./, value: s => s.slice(1)},
text: moo.default,
})
lexer.reset(`
Upon **further consideration,** #88 seems like a good idea.
Markdown(ish) syntaxes are the obvious motivating example…
`.trim())
console.log([...lexer]) /*
[ { type: 'text', value: 'Upon ' },
{ type: 'lstr', value: '**' },
{ type: 'text', value: 'further …
```
=> Proposal: default token types

README.md, moo.js, test/test.js, test/tosh.js
We recently added a [`value` transform](https://github.com/no-context/moo#transform).
This PR:
* Adds a `type` transform.
* Exposes `moo.keywords()`.
* Removes `Lexer#has()`.
The existing **value** transform takes the `text` and returns the `value`. By default, the text is used unchanged.
The new **type** transform takes the `text` and returns the `type`. By default, the type of the rule is used (e.g. `identifier`).
This is my preferred solution for #67 / #78. 
For example, you can create a customised version of `moo.keywords` which matches case-insensitively:
```js
const caseInsensitiveKeywords = map => {
const transform = moo.keywords(map)
return text => transform(text.toLowerCase())
}
let lexer = compile({
identifier: {
match: /[a-zA-Z]+/,
type: caseInsensitiveKeywords({
keyword: …
```
=> Add type transform

moo.js, test/test.js
Mark the final regex as `/u`, if every RegExp sets the `/u`flag, to solve #116.
If one RegExp has the `/u` flag, then all of them must have it.
Strings don't need any special handling.
=> Allow unicode flag if all RegExps use it

moo.js, package-lock.json, test/test.js
It's fairly natural to write code of the form:
```js
while (tok = lexer.next()) {
try {
parser.eat(tok)
} catch (err) {
throw new Error(lexer.formatError(tok, "Syntax error"))
}
}
try {
var program = parser.result()
} catch (err) {
throw new Error(lexer.formatError(tok, "Unexpected EOF")) // Not allowed!
}
return program
```
The second `formatError` call is not valid, because `tok` will be `undefined` here. Moo uses `undefined` to indicate that there are no more tokens, i.e. we've reached the end of the buffer.
There's no way to get Moo to format an error at the end of the file, after the last token, without manually constructing an EOF token. I propose letting `formatError` accept `undefined`, and silently interpret it as an EOF token.
Alternatively, we could introduce a …
=> formatError for undefined tokens

README.md
The documentation description just before the example states:
> * **`pop: 1`** removes one state from the top of the stack, and moves to that state. (Only `1` is supported.)
Also the typescript types agree it should be `1` not `true`.
=> Correct states example to use `pop: 1`

README.md
I noticed the link to the itt package in the readme doesn't work. It's not wrong though, the author just seems to have deleted the repo from github. Not sure what happened, but mapping an array to an object can be easily done with modern js without adding dependencies, so I just replaced the example.
=> Replace itt example with modern js example

moo.js
The function generated by keywordTransform provides does not include switch defaults so a non-keyword that is of the same length as a keyword will be checked against all possible keyword values longer than it.
With the existing output a non keyword like 'x' is checked against both `case "a"` and `case "bb"`:
```js
//> console.log(moo.keywords({KW: ['a', 'bb'] }).toString())
function anonymous(value
) {
switch (value.length) {
case 1:
switch (value) {
case "a": return "KW"
}
case 2:
switch (value) {
case "bb": return "KW"
}
}
}
```
With the changes in this commit it is only checked against `case "a"`.
```js
//> console.log(moo.keywords({KW: ['a', 'bb'] }).toString())
function anonymous(value
) {
switch (value.length) {
case 1:
switch (value) {
case "a": return "KW"
default: return
}
case …
```
=> Avoid fall through in keywordTransform

moo.js
In my project when using Nearley.js and moo.js together, after multiple times of parsing, sometimes the parser would throw an error.
I find that is due to moo.js, when it resets, the `queuedText` is not handled.
I think when it comes to reset and save, `queuedText` should be no different than `queuedToken` .
=> Fix a bug, `queuedText` is not handled in `reset`

moo.js, test/benchmark.js
As noted in #141, using `Function` causes issues for websites using a Content-Security-Policy that blocks `unsafe-eval` and it also appears that this is no longer the fastest approach.
This PR moves to using a Map, which [caniuse data suggests is supported](https://caniuse.com/mdn-javascript_builtins_map) in all major browsers released since 2015. I don't think the overhead of falling back to object attribute lookup is worthwhile unless you specifically support an ancient browser you know to be incompatible. I also altered the benchmark test to use `moo.keywords` since it was not doing so (although the difference to this benchmark is inside the noise when running in Node for me).
We're going to move to this Map approach in our project that uses `moo.js`, so we will have some real-world …
=> Use a Map instead of compiled switch-case for keywords
